run_backend:
  image: docker:dind
  before_script:
    - cd Backend/
    - docker build -t backend-image .
  script:
    - docker run -d -p 8000:8000 --name backend-container backend-image
  after_script:
    - docker stop backend-container
    - docker rm backend-container 

