version: "3.8"

services:

  webterminal:
    build:
      context: ./webTerminal
    networks:
      - mynet
    ports:
      - "5000:5000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  microservice:
    build:
        context: ./Microservice
    networks:
      - mynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynet
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./Backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
      FLASK_URL: "http://microservice:8000/api"
    networks:
      - mynet
    depends_on:
      - postgres
      - microservice

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Frontend
    networks:
      - mynet
    depends_on:
      - backend
      - webterminal
    ports:
      - "80:80"
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  


networks:
  mynet:

volumes:
  data:
